### PR TITLE
ups_lite: Add auto-shutdown

### PR DESCRIPTION
**Pull request by benallard**
## Description
When the battery level comes below a certain %, auto-shutdown to prevent loosing data.

## Motivation and Context
https://github.com/evilsocket/pwnagotchi/issues/650#issue-528008477
- [x] Someone else have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Setting the threshold way too high, and seeing it go down.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by benallard** [comment]
There seems to be an issue if the battery level is below the threshold, but the battery is currently charging. I need to account for that. Any idea if the ups-lite can tell something like that ?

**Comment by hyx0329** [comment]
Read ups-lite‘s manual. There is a jumper at the bottom side of the pcb. You need to connect them and ups-lite will tell you the situation through io4(BCM number, which is probably pin7). When the ups-lite is charging, you'll detect a high input at io4.

**Comment by benallard** [comment]
You probably mean that part of the doc:

Screenshot 2019-12-21 at 17 04 21

Unfortunately, I cannot read Chinese, and the pdf is made so that we cannot copy the text. Would you mind providing an english translation of that part ?

**Comment by hyx0329** [comment]
## Translated (with google and baidu):
### 3.1 charging and power adapter insertion detection function
It is recommended to use a power adapter with a power of 5V2A and above to charge UPS-Lite. Because when the lithium battery is low, the external power adapter not only supplies power to Pi, but also needs to provide some current for the lithium battery to charge. During the charging process, the red indicator light will be on, indicating that the battery is charging. When the lithium battery is fully charged, the green indicator light is on and the red light is off. __In addition, UPS-Lite has a power adapter insertion detection function. The IO4 (BCM number) of Pi will detect a high voltage input when it is plugged in, and a low voltage input when it is unplugged. To enable this function, the two pads on the back of UPS-Lite need to be shorted.__ See the figure below for details.

## the original text:
### 3.1 充电与电源插入检测功能
建议用功率在5V2A及以上的电源适配器给UPS-Lite充电。因为当锂电池电量较低时，外部电源适配器不仅要给pi供电，还需要提供部分电流供锂电池充电，充电过程中，红色指示灯会亮，表示电池正在充电。当锂电池充满电时，绿色指示灯会亮，红灯熄灭。另外UPS-Lite带有电源适配器插入检测功能，插入电源时pi的io4(BCM编号)会检测到高电平，拔出时为低电平，使能该功能需要短接UPS背面的两个焊盘，详细见下图。

**Comment by benallard** [comment]
My UPS-Lite died unexpectedly this week-end, I'm afraid I won't be able to follow-up on this Merge-Request unless I order a new one ...

**Comment by benallard** [comment]
@evilsocket @dadav, I suggest this to be merged as-is as the original bug has been fixed. There is room for improvement, but it requires soldering on the board. This could be fixed separately.

**Comment by hmax42** [comment]
isn't that a recursion in line 72 ?

**Comment by cyrinux** [comment]
Hi, as I will soon get this board, i'm interesting with the PR so thx @benallard 
Can you maybe just document somewhere that there is a solder to do?

**Comment by benallard** [comment]
There is no necessary soldering. At the moment it is so that if your battery level is below the threshold, your unit will be shutdown, even if it currently is charging. The soldering, and accompanying change to the plugin is a further improvement that can be separately done.

**Pull request merged**
