### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by LaurentFough**
Reasonably tame .editorconfig for help with editting the .py & especially the YAML files

## Description
Creates a reasonably tame .editorconfig for help with editting the .py & especially the YAML files

## Motivation and Context
May assist in the mitigation of issues created when users using IDEs/Editors to edit their config files, do not respect YAML file guidelines

## How Has This Been Tested?
- Sublime Text (macOS)
- Textmate (macOS)
- Visual Studio Code - Insiders (macOS)

## Types of changes
- [x] None

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by evilsocket** [comment]
why did you send a PR with the config to your own editor dude? each of us use whatever he wants, i use PyCharm but i'm not pushing my .idea folder here.

**Comment by LaurentFough** [comment]
@evilsocket:

It’s not the config for my editor.

editorconfig(.org) applies folder(project) level, root level, or global rules for editor/IDE configs to be applied for coding style coherence.

In this case I simply provided instructions for it to tell any editor that when the user is editing the `config.yml` or the `defaults.yml`
— it it should use spaces and not tabs.

It’s a small fix for the issues users have been having with the YAML and most of all it doesn’t override any of their other editor/IDE config.

**Comment by evilsocket** [comment]
it's not just for yml files, i see codestyles enforced for python files too

**Comment by LaurentFough** [comment]
Ya!, i was being overzealous.
I can remove that.

**Comment by LaurentFough** [comment]
Updated.
Removed *.py section
Removed * generic sane section

**Comment by evilsocket** [comment]
Thanks! :D

**Pull request merged**
