### PR TITLE
Theming via HTML

### PR DESCRIPTION
**Pull request by dipsylala**
Added to the handler - the following paths are now in play:

Endpoint `/`
Uses the 'theme' configuration in `web:` in config.yml. This defaults to 'default'
The pages are located in the template directory and take the format 'theme-{themename}.html'
The pages are static barring a couple of Flask additions (typically the name and the CSRF protection). JavaScript then calls the /state api and updates the screen accordingly to avoid refreshing the whole HTML.

Endpoint `/state`
Provides `/state/json` and `/state/png` for rendering results. `/state/png` is intended to replace `/ui` and the ui endpoint has been removed.

## Motivation and Context
- [x] Issue raised on https://github.com/evilsocket/pwnagotchi/issues/320 and numerous other issues regarding the configurability and customisation.

## How Has This Been Tested?
Has been tested across firefox/internet explorer. IE has issues (ha!) so some javascript had to be replaced.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

If you think the REST /state/json has benefit I can raise a separate documentation issue and update docs as needed.

### CODE REVIEW

**Comment by dipsylala** [comment]
***@Arttumiro and I are doing some additional testing on this before any merging, so I'd keep this handy and not merge for the moment. Especially as there's a lot of new functionality in the handler :)

**Comment by dipsylala** [comment]
Arttumiro was up and running - combination configuration issues and making sure pwngrid was the right version. 

I've noticed some symbols are being 'exchanged' for their colourful emoji equivalent in certain browsers (iPhone/Android seem particularly keen) - I'm checking for a way to prevent this. 

https://stackoverflow.com/questions/32915485/how-to-prevent-unicode-characters-from-rendering-as-emoji-in-html-from-javascrip looks useful. I'll do some testing on it later, but am unsure if this 'swapping' would be considered a deal-breaker for a merge.

image

**Comment by evilsocket** [comment]
@dipsylala there are several issues with this PR, mostly the fact that if the unit is not connected grid calls fail and everything else is stuck ... i'm trying to fix this. Next time please test better.

**Comment by evilsocket** [comment]
this just doesn't work, fields are missing everywhere ... wtf?

**Comment by evilsocket** [comment]
did anybody bothered testing this in MANU?

**Comment by dipsylala** [comment]
I had it in MANU - rebooted and was running - is grid failing because of it?

**Comment by evilsocket** [comment]
i'm fixing

**Comment by evilsocket** [comment]
it's full of bugs

**Comment by dipsylala** [comment]
I effectively disconnected it - but the issues I'm getting are in grid itself crashing if it can't resolve - that's before the handler is ever called. Is that what you're finding?

```

Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 90, in <module>
    agent.start()
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/agent.py", line 131, in start
    self.start_monitor_mode()
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/agent.py", line 115, in start_monitor_mode
    self.start_advertising()
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/mesh/utils.py", line 46, in start_advertising
    grid.set_advertisement_data(self._advertisement)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/grid.py", line 41, in set_advertisement_data
    return call("/mesh/data", obj=data)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/grid.py", line 27, in call
    r = requests.post(url, headers=None, json=obj, timeout=(30.0, 60.0))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8666): Read timed out. (read timeout=60.0)
```

**Comment by evilsocket** [comment]
that among other things ... i started pushing the fixes https://github.com/evilsocket/pwnagotchi/commit/53ce325010588c3fa10f6594e4828bf299618ff6

**Comment by evilsocket** [comment]
ok this PR has just too many problems, i'm reverting everything, i'm sorry

**Comment by dipsylala** [comment]
no no - totally ok. There's a chunk that we didn't account for during testing as I wasn't aware of particular use cases. I need to know more about what's going on with the grid when querying it and will dig deeper.

**Comment by evilsocket** [comment]
among the very long list of bugs i've found, there's a major issue with this approach. While with the current UI (image based from the display), if any plugin adds a new element that gets automatically shown on the web ui too, with this html approach each element needs to be individually and manually readded (like the memtemp for instance) ... this is ugly, i'm sure we can just work to make the image scale as we need.

**Comment by evilsocket** [comment]
also there was javascript duplicated everywhere (see how i refactored theme-default.html in 53ce325)

**Comment by dipsylala** [comment]
The CSS/JS was a deliberate design decision so that everything was self contained in the one page. Otherwise you're splitting everything across multiple folders. There's going to be repetition, but I was considering how it could be supported. Could refactor it all if that approach was preferred.

Re the new elements - they could be added if we expose the keys from the view. That gives us access to the elements then we can drop them into the JSON that's returned.

**Comment by evilsocket** [comment]
Re CSS/JS: *WHAT?* no man ... that's the way to do it, you don't put css and js inside the html and copy/paste it on 3 different files ... what if there's a bug in the javascript? do we need to fix it in three different files even if it's exactly the same? that's the ABC of antipatterns

Re new elements: no, that doesn't scale, we can't keep adding elements manually whenever new plugins are pushed, the whole thing must be automatic, and the only way we have to do that is the image approach as it just takes what the user already decided to render on the screen by enabling or disabling the plugins.

this whole approach is overall wrong

**Comment by dipsylala** [comment]
re the elements - it might be something that needs to be addressed regardless of the rendering. 

Rendering as HTML
If the element keys are made available, it can be up to the JavaScript to dictate how to render it - we're not restricted by the small pixel dimensions, so we can include a specific plugin notification area. We know what fields are provided by the plugins.

Rendering as PNG
If there's more feedback than what's available on the screen, a similar plugin notification area can be nominated, and the screen iterates through the plugin feedback. Otherwise, you're looking at plugin feedback potentially overlapping each other. If someone's using the mem/temp/cpu plugin that leaves little room for other stuff.

What I'm pondering here (and this is drifting off the HTML theming, though tangentially related) is knowing what plugin is responsible for what feedback, then at least you can group them. Otherwise it's not scalable as the plugins will crash into each other on the interface.

**Comment by evilsocket** [comment]
> it can be up to the JavaScript to dictate how to render it 

exactly, which means that if we want to support users plugins in the web ui, we need to write code in the core, which is the exact thing that the plugins system should avoid.

Going for html = introducing data duplication and most importantly logic duplication and coupling, we're not going to take the html path in core.

**Comment by dipsylala** [comment]
Totally cool - sorry, I didn't mean to come across as pushing for HTML in the core - that's off in a plugin now :) I think some of the issues you've raised might bite us in the PNG rendering though, if the number of plugins providing feedback grows.

That's why I thought grouping feedback based on plugin might come in handy. It gives you more flexibility in the core. Yes, it would be useful for other rendering, BUT if there are concerns around how to manage elements in a small space it could get you out of a hole.

**Comment by evilsocket** [comment]
nothing to be sorry abount, i was just being super clear about why i reverted the PR because i did appreciate your help a lot regardless of it :D

**Pull request merged**
