### PR TITLE
Improve manual mode detection for RPi3-4

### PR DESCRIPTION
**Pull request by ZerxXxes**
## Description

RPi3 and 4 does not have a USB data-interface so they have no way of start in manual mode.
This change makes pwnagotchi start in manual mode if a link is detected on the eth0-interface or if the file .pwnagotchi-manual is placed in /root/ (similar to the .pwnagotchi-auto file)

## Motivation and Context

Issue here: https://github.com/evilsocket/pwnagotchi/issues/365
- [x] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

NO
I only have access to RPi3 at the moment, needs to be verified on a RPi0W and maybe a RPi4.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by ZerxXxes** [comment]
When writing this I realised, looks like we have a race condition here?
https://github.com/evilsocket/pwnagotchi/blob/master/builder/pwnagotchi.yml#L298-L338
both launchers look for .pwnagotchi-auto to force auto-mode, and both will delete it when found

so if bettercap-lancher starts first, it will delete .pwnagotchi-auto and pawnagotchi-launcher wont be forced to auto as the file might already be deleted
and vice versa

**Comment by gkrs** [comment]
> When writing this I realised, looks like we have a race condition here?
> https://github.com/evilsocket/pwnagotchi/blob/master/builder/pwnagotchi.yml#L298-L338
> both launchers look for .pwnagotchi-auto to force auto-mode, and both will delete it when found
> 
> so if bettercap-lancher starts first, it will delete .pwnagotchi-auto and pawnagotchi-launcher wont be forced to auto as the file might already be deleted
> and vice versa

Actually the services should start in order. `pwnagotchi.service` has `After=bettercap.service` defined.

**Comment by evilsocket** [comment]
wait what? bettercap doesn't delete any file

**Comment by evilsocket** [comment]
oh the launcher

**Comment by evilsocket** [comment]
yeah just one of them should delete it, you're right, let me fix that

**Comment by evilsocket** [comment]
fixed with https://github.com/evilsocket/pwnagotchi/commit/a78a4b0b3e5cfbdfea481e140e6c02e0bdb1f72d

**Pull request closed without merging**
