### PR TITLE
Small fixes to voice and onlinehashcrack plugin

### PR DESCRIPTION
**Pull request by xBelladonna**
## Description

- Fix some typo in voice (rebooting prompt)
- Fix some typo in onlinehashcrack plugin log entry
- Add port onto end of IP (e.g. `192.168.44.1:8080`) in paw-gps plugin in log entry for clarity purposes to avoid confusion
- Announce that onlinehascrack plugins has loaded in logs
- Add facial expression when onlinehashcrack plugin uploads handshakes
  - This is hardcoded... perhaps should be added a new `ui.faces` entry in config may be better?

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
Issue #737 was raised to propose these changes.

Aim to correct spelling and improve the clarity/usefulness of logs.
Additionally aim to make pwnagotchi more cute/expressive when perform onlinehashcrack upload :^)

## How Has This Been Tested?

- First preliminary tests in VM using Ubuntu Server 18.04 and installation instructions for any GNU/Linux from documentation, but instead clone my fork and perform `pip3 install .`
- Properly tested in-situ on Raspberry Pi Zero W (Rev 1.1) with standard release image 1.4.1 after cloning my fork and perform `pip3 install .`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by evilsocket** [comment]
why this PR also changed the locales?

**Comment by xBelladonna** [comment]
Oh god, I changed the word in English "Ops" to "Oops" but then copypaste programming happened it seems... I changed all the translations in addition to the English and template lines and I don't know all of those languages so I don't know if they are correct. Would reverting that be best?

**Comment by evilsocket** [comment]
please send a cleaner PR, i can't merge this

**Comment by xBelladonna** [comment]
Thank you, I did want to just close because it was too messy. My apologies for this.

**Comment by evilsocket** [comment]
no apologies needed, no worries 👍 (and thanks for the PR!)

**Pull request closed without merging**
