### PR TITLE
Adding support for PaPiRus display

### PR DESCRIPTION
**Pull request by g0blinResearch**
**What?**

These changes add support for the 2 inch PaPiRus eInk display.

In order to use the display, you will need to install the drivers and required module, as documented [here](https://github.com/PiSupply/PaPiRus).

```
curl -sSL https://pisupp.ly/papiruscode | sudo bash
```

### CODE REVIEW

**Comment by dadav** [comment]
> **What?**
> 
> These changes add support for the 2 inch PaPiRus eInk display.
> 
> In order to use the display, you will need to install the drivers and required module, as documented [here](https://github.com/PiSupply/PaPiRus).
> 
> ```
> curl -sSL https://pisupp.ly/papiruscode | sudo bash
> ```

Everytime someone pipes from curl to root-shell a tux dies! I suggest we add a `display` parameter to the `create_sibling.sh` to create images for different displays and add the install-code directly, instead of pipe & root-shell.

**Comment by g0blinResearch** [comment]
Hah, ok - good point. That'd be pretty nice. I'll see about achieving that this evening for the PaPiRus.

**Comment by g0blinResearch** [comment]
@dadav would including the two required libraries under a drivers folder (similar to how the waveshare drivers are included) be acceptable? It's a little extra bloat, but would reduce complexity in the `create_sibling.sh` script. This is how I had it initially when testing, but decided to switch to using the system installed libraries while reinstalling yesterday.

**Comment by dadav** [comment]
> @dadav would including the two required libraries under a drivers folder (similar to how the waveshare drivers are included in #20) be acceptable? It's a little extra bloat, but would reduce potential complexity in the `create_sibling.sh` script. This is how I had it initially when testing, but decided to switch to using the system installed libraries while reinstalling yesterday.

If #20 is accepted, i see no reason why we shouldn't do that here too^^

**Pull request merged**
