### PR TITLE
Inkyphat subclass to incorporate timing changes.

### PR DESCRIPTION
**Pull request by dipsylala**
### Details:
This incorporates the changes suggested by https://github.com/evilsocket/pwnagotchi/issues/272

inky.py is subclassed and the first 2 lines of the Black timing settings are changed as per the recommendations by @neurovish. This avoids changing core inky files.

### Testing:
This has been tested on an InkyPhat over the course of 2 hours with no deterioration of the display quality.
Changes are limited to Inky so should not affect Papirus/WaveShare displays.

Comparison video of the changes available here: https://pwnagotchi.slack.com/archives/CNWNK0D5M/p1570986256445800?thread_ts=1570931518.310800&cid=CNWNK0D5M

### CODE REVIEW

**Comment by b0bje** [comment]
This makes so much difference! thanks so much!

**Comment by neurovish** [comment]
Nice! Thanks for finding a good way to bring this into the project.

**Comment by PeterAlfonsLoch** [comment]
this makes more ghosting, the complete black and complete white pahses are there to limit ghosting. i suggest a slow and fast refresh option in display.

**Comment by dipsylala** [comment]
@PeterAlfonsLoch I genuinely haven't seen any ghosting on either of my 2 inkyphats and I've soak tested for a few days.  Have you noticed something on yours?

**Comment by PeterAlfonsLoch** [comment]
Yes with the black phase there was less ghosting, i wopuld prefer that option to be available. i would understand if it would default to fast if no option defined.

**Pull request merged**
