### PR TITLE
New faces with more emotion

### PR DESCRIPTION
**Pull request by Leajian**
DejaVu Sans Mono compatible

### CODE REVIEW

**Comment by evilsocket** [comment]
hey did check this PR? Because most of the new faces are not rendered correctly

**Comment by caquino** [comment]
Maybe it requires a different font to work?

**Comment by Leajian** [comment]
I can't **really** test it, because I don't have an e-ink screen and I'm having problems running it via browser on usb0 right now (can't get ubuntu to recognize the device for some reason). My testing was changing the font to DejaVu Sans Mono in LibreOffice Writer and observing if the characters are recognized.

**Comment by dadav** [comment]
For me it's also not working. You can load the font via python and create some text with it. This faces produces "squares" :(

**Comment by dadav** [comment]
Use this script for testing:

```python
import sys

from PIL import Image,ImageDraw,ImageFont

TXT = " ".join(sys.argv[1:])
FONT = ImageFont.truetype("/usr/share/fonts/TTF/DejaVuSansMono.ttf", 28, encoding="unic")
CANVAS = Image.new('1', (250, 122), 0xff)
DRAW = ImageDraw.Draw(CANVAS)
DRAW.text((0,40), TXT, 0x00, FONT)
CANVAS.save("preview.png", "PNG")
CANVAS.show()
```

don't forget to use a virtualenv and install `pillow`

**Comment by Leajian** [comment]
Updated and tested with a slightly modified script by @dadav

**Pull request merged**
