### PR TITLE
Fix the weird looking COOL-face

### PR DESCRIPTION
**Pull request by dadav**
Please, please use the sunglase face as the cool face too!! The current one is sooo weird, i don't even get it...

### CODE REVIEW

**Comment by Leajian** [comment]
Finally, someone shared some feedback! :)
Originally, when I made this face, I had in mind the 'Feel like a sir' face, because I thought it was cool, but I was quite hesitant, because I was sure no one will get it. In that face there is actually a single eye glass piece or "monocle".
It's quite difficult to have emotion with only 4 characters for face.
The previous cool face was actually cool, but I hate repetition, since it was used in "looking right/left" face.
But, I'll look into that too, thanks for the feedback!

**Comment by dadav** [comment]
@Leajian You did great with all the other faces, but this one is strange :D

**Comment by evilsocket** [comment]
at least is unique! i'll replace it when we'll find something new and better XD

**Comment by Northwave** [comment]
Correct me if I'm wrong, but the cool face is only used when its investigating / deauthenticating ?
Maybe a face more looking investigative is right :D 
(◕_◉┐)    (/•ิ_•ิ)     (⚆__⚆)      (ಠ__ರೃ)      (◕__ರೃ)
Here some suggestions

**Comment by tjbenator** [comment]
I quite like the monocle face when it's deauthing someone, maybe "cool" isn't the right name for it? 

Emoji definition:
> Usually depicted with a small, intent frown and head slightly upturned, as if in careful inspection.

> May show that someone is pondering, considering, or questioning something, sometimes with a sense of skeptical or ironic observation or encouraging a closer look at some content. May convey a sense of sophistication or smug intelligence, e.g., smarty-pants.

https://emojipedia.org/face-with-monocle/

**Comment by dipsylala** [comment]
For looking, how about this? Then cool face has the opportunity to don sunglasses and look distinct from the others :)
Spacing to left or right of eyes help it look as if the head has turned.

(☉_☉ ) <- looking left 
( ⚆_⚆) <- looking right

**Comment by evilsocket** [comment]
i kind of like it a lot :D does it render on display?

**Comment by dadav** [comment]
right
left

**Comment by dadav** [comment]
maybe make him smile?

(☉◡☉ ) <- looking left
( ⚆◡⚆) <- looking right

**Comment by dipsylala** [comment]
Lol - it looks a lot more intense/scared when rendered on the screen with my original suggestion :)

**Comment by evilsocket** [comment]
i like it to be neutral when it's looking :D

**Pull request merged**
