### PR TITLE
Add configuration options to gps.py (position, vertical line spacing)

### PR DESCRIPTION
**Pull request by crahan**
## Description
Similar to https://github.com/evilsocket/pwnagotchi/pull/918, this pull request adds the ability to configure the position (via `main.plugins.gps.position`) and vertical line spacing (via `main.plugins.gps.linespacing`) of the gps plugin. It also corrects the default x-position values for some of the screens and removes redundant leading whitespace from the coordinate values (but keeps the ending space workaround in place).

## Motivation and Context

Fixes https://github.com/evilsocket/pwnagotchi/issues/921

- [x]  I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

Providing the ability for users to tweak the position and vertical line spacing of the gps plugin enables them to customize the plugin to their liking without the need for code updates. Together with https://github.com/evilsocket/pwnagotchi/pull/918 it also allows users to more easily match the output for the gps and memtemp plugins so lines properly align with each other.

## How Has This Been Tested?
This has been tested on a WaveShare v2 display on a Pi Zero W and Pi 3b. The default setup without any of the new configuration options was tested to ensure the plugin updates do not break the current version. Then each of the configuration options were tested (individually and together).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by evilsocket** [comment]
hi @crahan and sorry for the huge delay :D can you check this conflicts please? thank you!

**Comment by crahan** [comment]
Hi @evilsocket, thanks for considering this contribution.

I've resolved the merge conflicts. The issue was due to the update to `gps.py` as a result of pull request https://github.com/evilsocket/pwnagotchi/pull/967. My PR contains this fix as well and all should be good to go now. The hardcoded label positions will still be used whenever the user does not specify a customized label position.

**Comment by evilsocket** [comment]
thanks a lot!

**Comment by crahan** [comment]
Quick followup question. What would be the best way to contribute some documentation for the additional configuration options for both the `gps.py` and `memtemp.py` plugins?

**Comment by evilsocket** [comment]
@crahan definitely a PR to this repo would be the best and quickest :D https://github.com/evilsocket/www.pwnagotchi.ai

**Pull request merged**
