### PR TITLE
Changed webhook arguments, added exception handling, added logrotation

### PR DESCRIPTION
**Pull request by dadav**
see title

### CODE REVIEW

**Comment by dadav** [comment]
Added the logrotation by mistake into this PR, hope it's ok...

**Comment by evilsocket** [comment]
no it's not, log rotation done this way will split sessions and restart the demon while it's doing its things ... we need to handle that ourselves on session start as wrote in #527

**Comment by dadav** [comment]
Thats what i thought :D Fixed it

**Comment by evilsocket** [comment]
👍 thanks

**Comment by b33rANDfr13s** [comment]
Was log rotation confirmed for this commit?

I am currently unable to get log rotation operational - keep getting errors that prevent pwnagotchi from starting, erroring out in the 'setup_logging' function of util


sudo pwnagotchi --debug
`Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 44, in <module>
    utils.setup_logging(args, config)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/utils.py", line 124, in setup_logging
    file_handler = logging.FileHandler(config['main']['log'])
  File "/usr/lib/python3.7/logging/__init__.py", line 1079, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not dict
`

Note the section for enabling log rotation, from config.yml (spaced as shown in default.yml)
`    log:
      path: /var/log/newfile.log 
      rotation: 
        enabled: true 
        size: '10M'
`

**Pull request merged**
