### PR TITLE
Small fixes: correct typos and clarify plugin log entries/default configuration

### PR DESCRIPTION
**Pull request by xBelladonna**
Providing small fixes, correcting typos and adding more useful information to logs/default config.

## Description

  - Fix some typo in `voice.py` (rebooting prompt)
    - This requires recompiling locales due to change in `msgid`, however only English was changed, other locales were unmodified since I only speak three languages and cannot know what is correct for all.
  - Fix some typo in onlinehashcrack plugin log entry
  - Add port onto end of IP (e.g. 192.168.44.1:8080) in paw-gps plugin in log entry and default config for clarity purposes to avoid confusion
  - Announce that onlinehascrack plugins has loaded in logs
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))
Issue #737 was raised to propose these changes.
There are a few typos and slightly ambiguous information in logs/default config. This aims to correct those typos and clarify the ambiguous information to ensure there is only one way to interpret it.

## How Has This Been Tested?

  - First preliminary tests in VM using Ubuntu Server 18.04 and installation instructions for any GNU/Linux from documentation, but instead clone my fork and perform `pip3 install .`
  - Properly tested in-situ on Raspberry Pi Zero W (Rev 1.1) with standard release image 1.4.1.
    - Updated bettercap and pwngrid to latest versions available
    -  Finally, clone my fork and perform `pip3 install .`

I would appreciate if others could test this as well to ensure the changes do not break anything 😅 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by dadav** [comment]
@xBelladonna There is a conflict now :)

**Comment by dadav** [comment]
@xBelladonna Hey, sry I comment so late, but could you resolve the conflicts so we can merge this? :)

**Comment by xBelladonna** [comment]
Hi, sorry was asleep, will do soon

**Comment by xBelladonna** [comment]
@dadav Everything should be in order, thank you for letting me know

**Comment by dadav** [comment]
@xBelladonna One more time :D

**Comment by xBelladonna** [comment]
@dadav goodness, it should all be OK now!

**Pull request merged**
