### PR TITLE
Add whitelist support to onlinehashcrack plugin

### PR DESCRIPTION
**Pull request by neutralinsomniac**
## Description
Added the ability to whitelist specific SSIDs or BSSIDs to prevent upload of their handshakes to OHC

## Motivation and Context
Not everyone wants handshakes for their personal networks uploaded

## How Has This Been Tested?
Removed already-uploaded handshake files from /root/.ohc_uploads, added ssids to main.plugins.onlinehashcrack.whitelist, ran pwnagotchi and observed local debugging log messages verify the skipping of upload of whitelisted handshakes. then removed whitelist, restarted, and watched ohc plugin upload the previously-whitelisted handshakes as expected

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
https://github.com/evilsocket/pwnagotchi/issues/462
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. --> *will do this after this is at least approved (not necessarily merged)*
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by dadav** [comment]
Maybe put try/catch around the filtering. If the filename is fckd up, the code crashes! Rest looks good :)

**Comment by neutralinsomniac** [comment]
> Maybe put try/catch around the filtering. If the filename is fckd up, the code crashes! Rest looks good :)

nice catch!

**Comment by neutralinsomniac** [comment]
also of note, your catch affects the grid plugin as well:
```
[2019-10-30 19:03:15,225] [ERROR] grid: Not a supported capture file
[2019-10-30 19:03:15,698] [ERROR] error while reporting ap (ai:es:rn)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/grid.py", line 86, in report_ap
    'bssid': bssid,
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/grid.py", line 30, in call
    raise Exception("(status %d) %s" % (r.status_code, r.text))
Exception: (status 422) {"error":"422 "}
```

**Comment by dadav** [comment]
> :"4

will you fix the grid plugin too?

**Comment by neutralinsomniac** [comment]
> will you fix the grid plugin too?

done here: https://github.com/evilsocket/pwnagotchi/pull/472

**Pull request merged**
