### PR TITLE
Make wigle.py work

### PR DESCRIPTION
**Pull request by xfox64x**
There were issues with the formatting of the CSV data, and if the original module could successfully post to WiGLE, it would be unnecessarily inflating the WiGLE processing queue with tiny files. A more efficient idea that isn't toxic to the WiGLE community is to collect all CSV lines ready to upload, put them in one "file", and then submit it for processing. The GPS accuracy isn't 0; that would be 0 meters of error, so let's at least increase that to something plausible. Also, removed spaghetti, wasteful assignments, and general waste.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by xfox64x** [comment]
I'm not going to follow your contributing guidelines, so take the fix or leave it. Don't really care, either way; my version works.

**Comment by virtadpt** [comment]
Does this handle the case where the Pwnagotchi isn't tethered via Bluetooth, but connects in manual mode and does a bulk upload to the Grid, et al?

**Comment by evilsocket** [comment]
"I'm not going to follow your contributing guidelines" 👋

**Comment by evilsocket** [comment]
@dadav check this out, if the fixes are valid please copy/paste them in a proper PR so that you'll get credits for it ^___^

**Pull request closed without merging**
