### PR TITLE
Added support for waveshare V4

### PR DESCRIPTION
**Pull request by timothfee**
## Description
Added files that would remove the confusion around the support for the waveshare_v4 (the screen I use with my pwnagotchi).

## Motivation and Context
I felt like people were not utilizing their V4 screens due to a misconception they wouldn't work, or maybe they felt like they needed to do a whole bunch of work to get it functioning, when in reality all you need to do is use the waveshare_v3 settings.

## How Has This Been Tested?
Created my own repository containing my changes and flashed my pwnagotchi with my new repository. Went into the config.toml and changed my screen setting to "waveshare_v4". I did this on a Linux machine, and utilized my raspberry pi 0w.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by Yzord** [comment]
thanks

**Comment by Yzord** [comment]
Hmm, i can't get it to work. I placed your files in the corresponding directories and edited the config.toml file with "waveshare_v4", but it isn't doing anything. The screen is not recognized. Any idea?

**Comment by timothfee** [comment]
I appreciate the feedback, I am gonna do a little more testing. I will let you know!

**Comment by tcsabina** [comment]
> Hmm, i can't get it to work. I placed your files in the corresponding directories and edited the config.toml file with "waveshare_v4", but it isn't doing anything. The screen is not recognized. Any idea?
> 
> `unsupported display type waveshare_v4`

Try this:
1) Shut down the pwnagotchi service (systemctl stop pwnagotchi)
2) Replace the source located in /usr/local/lib/python3.7/site-packages/pwnagotchi with the changes from this PR
3) Restart the pwnagotchi service and verify screen is correctly initialised and pwnagotchi displayed on it

**Comment by widhalmt** [comment]
I have a v4 and the changes here didn't work out for me. But the ones in #1135 did.

**Pull request closed without merging**
