### PR TITLE
Re-Add Network related files to backup

### PR DESCRIPTION
**Pull request by deveth0**
## Description
I'm not quite sure, why those files have been removed in this commit:
https://github.com/evilsocket/pwnagotchi/commit/c954bf8ffa424b7cd9ec3aadc9d15f0b2f2e9eb9#diff-179da8459e84bc41a473e2921dce8b57

Given that you'd like to restore the unit without the need to change anything afterwards, I'd like to see those files included in the backup.

## How Has This Been Tested?
Tested with latest RC

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by evilsocket** [comment]
restoring host files when the hostname is not set yet can cause problems, that's why we removed it from the backup

**Comment by dadav** [comment]
I think we should only backup files which came from the project directly.

**Comment by deveth0** [comment]
Sure, for backups I'd totally agree, but this way updates as described in the documentation are a real pita...
Probably the way of updating should be changed in a way, that there is some kind of script on your pi which you can run to update. It would need to stop the wifi device, restart it with a real connection and then perform the required updates.

**Comment by evilsocket** [comment]
not sure what's the pita in "scp your-files pi@10.0.0.2:/wherever" given that you need some sort of ssh connectivity to the unit anyway

**Comment by evilsocket** [comment]
as i said i know as a matter of fact that if i merge this, it will cause problems for others (this script used to backup these files, we removed them for this reason).
if you want to name your unit not there's a new procedure which is config.yml based and only requires you to create a file in the boot partition https://pwnagotchi.ai/configuration/#initial-configuration

**Comment by evilsocket** [comment]
there are other parts of the docs that we added (see previous links)

**Comment by deveth0** [comment]
OK, I'll dig into it, thx :)

**Pull request closed without merging**
