### PR TITLE
Add image creation script

### PR DESCRIPTION
**Pull request by dadav**
I automated the image creation process in a small script. It uses the qemu-user-static method you mentioned in your tweet.

All you need now is:
`./create_sibling.sh -n beta -o pwnagotchi-beta.img `
It will use the latest raspbian.

It would be good if someone could test the output on a pi, cuz i need to order another sdcard first ^.^

### CODE REVIEW

**Comment by caquino** [comment]
That's actually awesome, this + travis-ci and we could have automated image releases :)

**Comment by evilsocket** [comment]
this is amazing!

**Comment by friedphish** [comment]
Ok, haven't had time to debug this yet, but the images created currently don't work on the pi0w. 

They seem to boot fine, and a cursory check of the filesystem shows everything looking totally fine, but they absolutely refuse point-blank to do anything. You can ping it over the usb interface, but not access SSH - even with the "ssh" file in /boot, and the pwnagotchi/bettercap webuis aren't accessible.

**Comment by stackofcats** [comment]
I guess that's because the PARTUUID in /etc/fstab within the image has to be updated.
Afterwards (just fetched the new one via blkid from the loop devices), I was able to boot the generated image.

**Pull request merged**
