### PR TITLE
first image build

### LINKED ISSUE #1048: create CI on github actions
Hi @evilsocket !

I would like to contribute to pwnagotchi and do some improvements as I have a lot of knowledge in CI.
But first I would like to align here with you not that I am spending my time for nothing in the end.

I have seen that you are using Travis to build an image which is already very nice. But I think it would be better to create this images more often (every pull request and on the mainline), also to do some checks (code check, style check, are there dependency issues etc.). Testing on real hardware is simpler too as I can get a image directly from the github server and I do not need to setup something at home.
As Github actions is already very well integrated in Github, I propose to switch from Travis to Github Actions as it is simpler to use and it has nearly no restrictions.
The process to create a new release is also improved a lot if you have some q-gates already setuped.

To summerize my changes:
- switch from Travis to Github Action
- run CI (create image, code check, style check, ...) on every pull request and on the mainline -> result is directly shown on Github (green/red)
- add some more CI tasks

Please tell me what you are thinking about it. I think this will fix a lot of issues with dependencies (like numpy is not working in 1.5.5) and everybody will get a newer image anytime.

### PR DESCRIPTION
**Pull request by peterus**
## Description
this PR will fix #1048 (setup a new CI job on Github Actions).

## Motivation and Context
- [X] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
CI will run some tests.
PR still in progress

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by peterus** [comment]
@evilsocket can you check if Github Actions ins activated in this repository? I can see that there is nothing running.

**Comment by matglas** [comment]
If you have actions enabled on your fork will it run there too? Like during preparation of the PR?

**Comment by matglas** [comment]
Hey I just noticed on your fork that the actions are working. I see your last build didnt work correctly yet. Are you planning on some more changes?

**Comment by incyi** [comment]
I made a different variant of this github actions. I tried to follow the way how it is currently builded.

**Pull request closed without merging**
