### PR TITLE
Fixed bugs and made the script work out-of-the-box for the first time

### PR DESCRIPTION
**Pull request by dadav**
I fixed the bugs which were mentioned in the other PR (#7 )

AI should also work now out of the box.
On the first boot, tensorflow and opencv will be reinstalled in the correct arch, this will take about 15mins.

Your ssh credentials are pi:raspberry,
you  should change them ^^

### CODE REVIEW

**Comment by andr3w-hilton** [comment]
Huge thanks for this mate, I'll give it a test this evening, I was up late last night trying to make sense of the errors I was seeing etc but failing miserably. Really appreciate your work on this! :-)

**Comment by dadav** [comment]
Maybe it's better to start a real virtual machine via qemu-system-arm, ssh into it and provision all the things. This way we shouldn't have problems with tensorflow etc.

What do you think?

**Comment by dadav** [comment]
it's also not complicated: http://graznik.de/posts/emulate-raspberry-pi-with-qemu/

**Comment by evilsocket** [comment]
i tried, it's doable if you do not compile stuff, when you start compiling stuff it takes forever

**Comment by yavadan** [comment]
hmm, i tested the new script but it seems to exit here

`Collecting gast==0.2.2
  Downloading https://www.piwheels.org/simple/gast/gast-0.2.2-py3-none-any.whl
Installing collected packages: gast
Successfully installed gast-0.2.2
+ xargs '-I{}' --max-args=1 --max-procs=2 pip3 install '{}'
root@kali:~/Downloads# 
root@kali:~/Downloads# 
`

**Comment by andr3w-hilton** [comment]
Your new fixes worked perfectly. I have everything up and running without any issues. He's already munched through all of my wife's ;-) @evilsocket and @dadav can't thank you enough, it's been a fun few days. And now the fun can really start. :-)

**Comment by evilsocket** [comment]
ahah @andr3w-hilton my partner got crazy about it too :D hope you're gonna have lots of nice walks and fun! :D

**Comment by CarlosS7** [comment]
I just wanted to say that this has been so much fun, I've also learned a
lot, even though I have not been able to get it to connect to the internet,
therefore I am waiting for the pros to make it work (=$). So I believe
that @evilsocket should be very proud of his baby, that has touched and
will continue to touch so many lives, and for the improvement
(knowledge-wise) of the community!

**Comment by evilsocket** [comment]
@CarlosS7 you made me literally melt, thanks for your words.

**Comment by lucataco** [comment]
@yavadan yeah it might look like it hangs at that line, but if you keep waiting it goes on and creates the .img

**Comment by yavadan** [comment]
> @yavadan yeah it might look like it hangs at that line, but if you keep waiting it goes on and creates the .img

uh oh... haha i guess i should have not rebooted the kali vm in that case, oh well ill give it another go and see. thanks again guys!

**Comment by andr3w-hilton** [comment]
I do seem to have one final question. I still cant seem to get the magic internet script to run successfully. I have the pwnagotchi attached via usb to my linux laptop and when I run the script it says **Cannot find device "enp0s20f0u1"** should I be changing the interface in the script to reflect my interfaces? as in usb0 and wlan0?

**Comment by CarlosS7** [comment]
Not sure if it has to do with setting a fixed MAC address, I have not been
able to give this a try:

https://www.raspberrypi.org/forums/viewtopic.php?t=199588

**Comment by evilsocket** [comment]
@andr3w-hilton yes

**Comment by dadav** [comment]
> hmm, i tested the new script but it seems to exit here
> 
> ```
> Collecting gast==0.2.2
>   Downloading https://www.piwheels.org/simple/gast/gast-0.2.2-py3-none-any.whl
> Installing collected packages: gast
> Successfully installed gast-0.2.2
> + xargs '-I{}' --max-args=1 --max-procs=2 pip3 install '{}'
> root@kali:~/Downloads# 
> root@kali:~/Downloads# 
> ```

It does a lot of things parallel here and spams the stdout with the status. I redirected it to /dev/null, thats why you won't see anything. You can comment the ">/dev/null" part out and debug the script if you thing you get an error

**Comment by dadav** [comment]
> I do seem to have one final question/issue. I still cant seem to get the magic internet script to run successfully. I have the pwnagotchi attached via usb to my linux laptop and when I run the script it says **Cannot find device "enp0s20f0u1"** should I be changing the interface in the script to reflect my interfaces? as in usb0 and wlan0?

Plugin your raspberry. Open a shell and write ip addr. You should the name of the new device in the last line.

Then write sudo ./linux_connection_share.sh <the_ip_addr_iface> <internet_iface(e.g. wlan0)>

**Comment by andr3w-hilton** [comment]
> @andr3w-hilton yes

when I change the contents to
`# name of the ethernet gadget interface on the host
USB_IFACE=${1:-usb0}
USB_IFACE_IP=10.0.0.2
USB_IFACE_NET=10.0.0.0/24
# host interface to use for upstream connection
UPSTREAM_IFACE=${2:-wlan0}
`
I get the error RTNETLINK answers: File exists 

I have also copied the ssh file over to the /boot dir but it seems to disappear each time I boot the pwnagotchi without granting me ssh access, I just keep getting the connection refused. 

I'll keep working on it.

**Pull request merged**
