### PR TITLE
Script improvement and bugfixes

### PR DESCRIPTION
**Pull request by dadav**
Found some bugs. Also, script must be run as root now, because we did everything with sudo anyway. Because the script was moved into scripts-dir, it was creating stuff in this directory.

### CODE REVIEW

**Comment by friedphish** [comment]
Going to test this version now, have a bunch of spare SD cards and pi0w's to test it across!

**Comment by xenDE** [comment]
why you kill if not root and also use sudo?

i tested today with fresh debian 10.1 vm and default user has no sudo rights.

so better uses only "if not UID=0: exit 1 " ?

**Comment by friedphish** [comment]
Update on testing: image creation creates an image, but as of this time the image is not functional (tested using a few different SD cards and pi0w's). 

I ran into some snags with Qemu segfaulting the first couple of tries, but that cleared itself up eventually after rebooting the host a bit. 

I'm unsure at this time if the issue is with the created image (which *looks* to be fine), or dodgy hardware. The pi0w's and SD cards are brand new though, so I'm going to guess it is the image.

When I connect the device in USB gadget mode, it does present a network interface on Ubuntu, and I can ping it. However, "ssh" and other services appear to not be running.

I'll leave one powered on overnight, and in the morning dump the SD card and see if there are any logs or whatever that could indicate runtime issues.

**Comment by dadav** [comment]
> Update on testing: image creation creates an image, but as of this time the image is not functional (tested using a few different SD cards and pi0w's).
> 
> I ran into some snags with Qemu segfaulting the first couple of tries, but that cleared itself up eventually after rebooting the host a bit.
> 
> I'm unsure at this time if the issue is with the created image (which _looks_ to be fine), or dodgy hardware. The pi0w's and SD cards are brand new though, so I'm going to guess it is the image.
> 
> When I connect the device in USB gadget mode, it does present a network interface on Ubuntu, and I can ping it. However, "ssh" and other services appear to not be running.
> 
> I'll leave one powered on overnight, and in the morning dump the SD card and see if there are any logs or whatever that could indicate runtime issues.
> 
> Should also be noted that the e-ink display doesn't seem to come to life at all, indicating something is up there. Tried with a couple displays, no dice with any of them.

Thanks man, gonna look into it on the weekend!

**Comment by andr3w-hilton** [comment]
I can confirm what @friedphish is experiencing. I am having the exact same issues. The script appears to complete without any errors (that I can see). I power up the pwnagotchi, the screen doesnt come to life at all, I cant seem to connect to the web interface but I can ping the IP. 
I am using pi0w with a V2 waveshare (black/white) screen. 

I have tried running it with 3 different SD cards ranging from a 16gb noobs, 16gb samsung and a 32 gig samsung.

**Comment by dadav** [comment]
Could you plugin a hdmi cable and check what is happening? @friedphish @andr3w-hilton

**Comment by friedphish** [comment]
Unfortunately I don't have a HDMI screen where I am at the moment, unless @andr3w-hilton can help with this I'll have to wait until I get a chance to pick one up or borrow one.

**Comment by andr3w-hilton** [comment]
Yeah no problem at all, I'll pick up my cable from the office and try to test it at lunchtime or at worst I'll be able to test it tonight and report back.

**Comment by friedphish** [comment]
Connected a serial cable to mine and booted it, it basically never makes it to a login prompt. 

It either hangs up on the "Launching /sbin/init..." part, or dies after bringing up the USB interface. I'll capture a few more samples and update this comment with some gists/pastebins of the boot-console output.

**Comment by friedphish** [comment]
Update: over serial, I got it to actually get as far as sulogin, and logged in (had to edit the shadow file on the SD card first). The "pwnagotchi" software was not running, and when I ran the launch script manually, all sorts of hell broke loose. In the paste below is the output of me trying to make sense of whats going on here, which contains... Some errors going on. It appears that the USB interface is causing some issues... I think?

There is nothing created in pwnagotchi.log file at all.

It should also be noted that its only one in every few tries that we get this far.

https://pastebin.com/yMwXDzhf

**Comment by Mila432** [comment]
the script is kind of broken as of now , many errors but yeah 
>THIS IS STILL ALPHA STAGE SOFTWARE, IF YOU DECIDE TO TRY TO USE IT, YOU ARE ON YOUR OWN, NO SUPPORT WILL BE PROVIDED, NEITHER FOR INSTALLATION OR FOR BUGS

after you get it running it will crash because it cant read the log file , if you create the log file , it will try to parse a session id but again will crash because there is no input , after that there will be a division by zero

**Comment by dadav** [comment]
> 
> 
> Update: over serial, I got it to actually get as far as sulogin, and logged in (had to edit the shadow file on the SD card first). The "pwnagotchi" software was not running, and when I ran the launch script manually, all sorts of hell broke loose. In the paste below is the output of me trying to make sense of whats going on here, which contains... Some errors going on. It appears that the USB interface is causing some issues... I think?
> 
> There is nothing created in pwnagotchi.log file at all.
> 
> It should also be noted that its only one in every few tries that we get this far.
> 
> https://pastebin.com/yMwXDzhf

Thanks a lot! Could you also upload /var/log/messages and /var/log/dmesg? :)

**Comment by stackofcats** [comment]
Can you check whether https://github.com/evilsocket/pwnagotchi/pull/4#issuecomment-534986363 applies?

**Comment by dadav** [comment]
> 
> 
> Can you check whether [#4 (comment)](https://github.com/evilsocket/pwnagotchi/pull/4#issuecomment-534986363) applies?

Good catch! Gonna update the script :)

**Comment by friedphish** [comment]
@stackofcats ah, confirmed! they are incorrect! Going to mount the device and edit them.

@dadav Logs here: https://pastebin.com/PYGav79c

**Comment by friedphish** [comment]
Ok, progress! I had to do the magic internet sharing to install a missing PIL dependency (libopenjp2-7-dev), and got as far as "Bootstrapping AI" by manually running "main.py" over SSH before it choked on an "Illegal Instruction" error.

I'm reinstalling the python dependencies *on device* (from requirements.txt) for now, and seeing where that takes me.

**Comment by friedphish** [comment]
Another missing dep: tcpdump package. I disabled the AI for now while I work out why tensorflow is giving an illegal instruction error, and it works perfectly.

As for why tensorflow is broken, here is my hypothesis: when building in Qemu, we use the armhf package, wheras the Pi wants the armv6l package. I'll try fix this shortly to confirm it, just been having trouble getting the replacement package to install without overheating the little board.

**Comment by yavadan** [comment]
> > Can you check whether [#4 (comment)](https://github.com/evilsocket/pwnagotchi/pull/4#issuecomment-534986363) applies?
> > With that changes I got the image running (V2 display).
> > Apart from the uuid thingy and the log creation, I only had issues with tensorflow so far ("Illegal instruction" fail), which doesn't seem that uncommon on pis, and two cpu and memusage commands in the screenrc that weren't found.
> > Oh yeah, a library was missing: libopenjp2-7.
> > I don't think I changed more than that, can verify all my changes this evening though.
> 
> Can confirm the missing memusage and cpuusage commands. Having a hard time to find information about them online, does someone know where i get them from?
> 
> Thx, for mentioning the missing library!!

housekeeping commands taken from
https://gist.github.com/GermaniumSystem/8e9c2f545889319c0eed1b433c0672d7

echo -e "#\!/bin/bash\ngrep 'cpu ' /proc/stat | awk '{usage=(\$2+\$4)*100/(\$2+\$4+\$5)} END {print usage \"%\"}'" > /usr/local/bin/cpuusage
chmod +x /usr/local/bin/cpuusage
echo -e "#\!/bin/bash\nfree | awk 'FNR == 3 {print \$3/(\$3+\$4)*100 \"%\"}'" > /usr/local/bin/memusage
chmod +x /usr/local/bin/memusage

**Comment by dadav** [comment]
>  armv6l package. I'll try fix this shortly

I had this error too. The workaround was using the "--no-cache-dir" option. Does this help?

**Comment by dadav** [comment]
Tensorflow has to be installed via:
https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-1.14.0-cp34-none-linux_armv6l.whl

see: https://www.tensorflow.org/install/pip

**Comment by evilsocket** [comment]
@dadav not really, you can just install it from pip3 via https://www.piwheels.org/****

**Comment by dadav** [comment]
> 
> 
> @dadav not really, you can just install it from pip3 via https://www.piwheels.org/****

But will this install the same package as in the qemu installation? For @friedphish the packages seems to differ and cause problems :(

**Comment by 5h4d0wb0y** [comment]
I tried to use your script unsuccessfully. Below the screenshots via hdmi:
IMG_20190925_135347
IMG_20190925_135417
IMG_20190925_140306

**Comment by natur3kid** [comment]
That happens when the Part UUID is wrong.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stackofcats** [comment]
> Can confirm the missing memusage and cpuusage commands. Having a hard time to find information about them online, does someone know where i get them from?

Well they don't really matter, so just comment them out or create your own ;)

**Comment by andr3w-hilton** [comment]
@dadav sorry for the slow reply. I didn't get a chance to do any testing with the hdmi at lunchtime. Just got back and read through all of today's messages. Happy to still test it if you need it, but thinking maybe you're past that stage now.

**Comment by sshawuk** [comment]
I was having the issues as described above. Fixed the PARTUUID in /etc/fstab to get booted but then encountered the Illegal Error when trying to run the main script. 

I've purged the installed tensorflow and reinstalled it directly on the device and now all is well!
I think their might be another difficulty with the imported cv2 package, but I need to dig deeper first, but the script is running fine, screen is on and displaying perfectly :)

**Comment by sshawuk** [comment]
Purged opencv-python and reinstalled directly on the device and bingo, everything is working a treat now!!

For anyone having the hash issue when pip installing tensorflow, or opencv, you can copy the URL that's returned in the error, ditch the hash part of the url and pip3 install the URL to the wheel.

**Comment by CarlosS7** [comment]
Just wondering, is opencv needed for what Pwnagotchi does? May it be an unnecessary dependency of the gym package?

**Comment by evilsocket** [comment]
@CarlosS7 yes, it is a dependency of gym, pwnagotchi itself doesn't use it, but still gym doesn't seem to work without

**Comment by andr3w-hilton** [comment]
> I was having the issues as described above. Fixed the PARTUUID in /etc/fstab to get booted but then encountered the Illegal Error when trying to run the main script.
> 
> I've purged the installed tensorflow and reinstalled it directly on the device and now all is well!
> I think their might be another difficulty with the imported cv2 package, but I need to dig deeper first, but the script is running fine, screen is on and displaying perfectly :)

Can I ask how you fixed the PARTUUID? my script completes without any errors but I cant seem to connect to the pwnagotchi at all. I can ping the usb0 interface but ssh not working or the http webui? Is it something I can fix in the script before I run it?

**Comment by sshawuk** [comment]
So I flashed the image, unmounted and remounted it and ran "sudo blkid". Take a note or the PARTUUID reported in the output for each of the partitions on your SD card. With the card mounted, edit /etc/fstab, replacing the two values with those you've just noted down. Unmount, insert, enjoy....well, after you've purged and reinstalled tensorflow, opencv, and handled a few missing dependencies that im still wrapping my head round

**Comment by dadav** [comment]
> @dadav not really, you can just install it from pip3 via https://www.piwheels.org/

the problem seems to be that if i chroot into the image, uname gives me arm7l and pip therefore installs the arm7l wheel of tensorflow, but we need arm6l :(

**Comment by andr3w-hilton** [comment]
editing the fstab worked a treat and got me up to this part now which I'm stuck on, looking online it seems like something might have been installed out of sync but can't really find any info regarding directly to the pwnagotchi installa that have been happening. Have any of you seen this on your installs? https://photos.app.goo.gl/MTF8MThkcMHWmGai7 this is the stage I'm stuck on now.

**Comment by andr3w-hilton** [comment]
I'm getting there, so now I'm logged in via and viewing the CMD line via HDMI. I still can't seem to give it any internet connectivity though. When booting I get a  "Failed to start dhcpcd on all interfaces" error. So still no SSH connection either.

**Comment by andr3w-hilton** [comment]
Can I ask a really stupid question, I think I am at the stage now where I need to share my internet with it, (still no ssh connectivity though) i cant get the script to work at all and keep getting **Cannot find device "enp0s20f0u1"**
 
I've tried changing the interfaces to reflect the actual interfaces I have as in usb0 and wlan0 but still nothing, the error at that point says something about the file already existing. I spent last night working through the manual approaches for the networking and changed the wpa_supplicant file, it now has a wlan0 showing but still not getting an IP for the interface. 

Am I missing something obvious? Going to spend my study afternoon in work today to carry on, it's so frustrating but I am learning loads so quess its all working out ok.

**Pull request merged**
