### PR TITLE
vibrate plugin for haptic feedback without needing a screen

### PR DESCRIPTION
**Pull request by 0xRoM**
## Description
Solder small vibration motor to pin 40 (GPIO 21) and ground (pin 39)
this will vibrate the motor every time a handshake is captured so you no longer need to look a the screen or even have one!

## Motivation and Context
I wanted it

## How Has This Been Tested?
work on mine

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide

### CODE REVIEW

**Comment by xenDE** [comment]
nice idea!

can you give a link to an example vibration motor?

but can you bring the sleep()'s in background?
other plugins that wait for "on_handshake".

don't know how to do this in python.
i does it with a background shell script on my audio plugin, so the plugin does not need to wait for the end of playing sound.

**Comment by 0xRoM** [comment]
@xenDE I used https://www.amazon.co.uk/gp/product/B074M24S21/

probably can't use sleep's in background as they are needed between turning motor on and off so get 2 BUZZ's (they are only half a second each so shouldn't really impact performance)

p.s.  this plugin probably won't get merged as I have no idea how to resolve the conflits

**Comment by evilsocket** [comment]
please rebase

**Comment by 0xRoM** [comment]
"rebase"?

**Comment by evilsocket** [comment]
there are conflicts

**Comment by evilsocket** [comment]
you need to update your master with my master and reapply your edits

**Comment by 0xRoM** [comment]
I don't care that much, not worth effort

**Comment by evilsocket** [comment]
you don't *have* to send PR you know?

**Comment by 0xRoM** [comment]
hence closing it, might as well tidy up after myself at least. 
I don't know all this git stuff, if someone wants it codes here.. grab it if you want.

**Pull request closed without merging**
