### PR TITLE
Add CSRF token for web ui

### PR DESCRIPTION
**Pull request by python273**
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie

not implemented for plugins, since POST requests are not supported

### CODE REVIEW

**Comment by dadav** [comment]
@evilsocket thoughts?

**Comment by evilsocket** [comment]
as discussed with @python273 i'm considering just migrating the web ui to flask in order to use its middlewares so we don't have to implement all http security ourselves like in this PR

**Comment by dadav** [comment]
Sounds like an awesome idea! I like flask :)

**Comment by evilsocket** [comment]
fixed by https://github.com/evilsocket/pwnagotchi/pull/519

**Pull request closed without merging**
