### PR TITLE
Added plugin PAW GPS

### PR DESCRIPTION
**Pull request by leon-th**
## Description
I added the plugin paw-gps and added one option to the config file

The plugin saves every time a handshake is captured, the gps position from the smartphone over the paw server

## How Has This Been Tested?
I tested the plugin myself on a RPI Zero W with the Paw server running on my Sony Xperia with the bt-tether plugin

## Types of changes
New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by spees** [comment]
Is there any iPhone support with this? As far as i can tell, PAW is only available on Android. I am working on a solution that will work for both.

**Comment by leon-th** [comment]
Paw is only available on Android. I don't have an IPhone if you could provide me information how I could request the GPS Location from IOS, could I maybe integrate IOS.

**Comment by spees** [comment]
Making it work with iPhone takes a similar approach but still a complete rewrite of what you have done and no longer using PAW.

**Comment by leon-th** [comment]
If you could say me what app on IOS is avaible for something like this i could integrate this

**Comment by spees** [comment]
Thats the thing. As far as i know, there isnt. A GPS sharing over TCP/IP would be required. I actually prefer using serial since that is supported by bettercap as well, but that has its own issues. That is supported on all devices and requires no weird script/hack on the device side either. Also includes all other information by default instead of only latitude and longitude.

**Pull request merged**
