### PR TITLE
Added ability to provide path to raspbian.img

### PR DESCRIPTION
**Pull request by Leajian**
For people that are testing and don't want to download it again.

### CODE REVIEW

**Comment by dadav** [comment]
You only need to download the image once. It runs wget with the "-c" option, so it won't re-download.

**Comment by Leajian** [comment]
Indeed, but what I had in mind was for people who don't want to download it at all.
For example, I already had it, so it would be a waste of time.
Also, latest doesn't mean the greatest, let's say some bugs are introduced. Therefore, there should be an option to easily select the image of your preference.

**Comment by lucataco** [comment]
Im new here, hoping to help you all run and test the script for others to enjoy!
Like others, with this version of the script I had to mount the sd card to set a passwd for root, edit /etc/fstab to replace the PARTUUIDs with /dev/mmcblk0p1( and 2), apt-get install libopenjp2-7-dev once booted, and re-install opencv and tensorflow, finally run: 'sudo -H -u root /usr/bin/screen -dmS pwnagotchi -c /root/pwnagotchi/data/screenrc.auto' and profit!

**Comment by Leajian** [comment]
@lucataco Aw man, I wrote about this problem with fstab at README.md in Random info section, but I'm still waiting for @evilsocket to merge the pull request. But yes, PARTUUIDs do get messed up for some people.

**Comment by dadav** [comment]
Already made a fix for the uuid problem, but still want to fix the tensorflow thing before PR...

**Comment by friedphish** [comment]
@dadav maybe a "sed" line in the script to disable the AI mode (for now) in the created images while we work out the tensorflow thing? 
A ~possible solution to the tensorflow thing is to download the tensorflow wheel with wget and install it that way during the image creation, thus bypassing pip buggering up.

**Comment by dadav** [comment]
> @dadav maybe a "sed" line in the script to disable the AI mode (for now) in the created images while we work out the tensorflow thing?
> A ~possible solution to the tensorflow thing is to download the tensorflow wheel with wget and install it that way during the image creation, thus bypassing pip buggering up.

Good idea, but cant install armv6 wheel on armv7 architecture; pip will say no... So my current solution is to download the correct packages and install it on first boot. Needs some testing tho..

**Comment by friedphish** [comment]
Let me know if you need any help testing, have plenty of spare Pi's, displays and SD cards.

**Comment by dadav** [comment]
> Let me know if you need any help testing, have plenty of spare Pi's, displays and SD cards.

feel free to checkout my fork^^

**Comment by natur3kid** [comment]
How does one change the root password on a mounted SD?
Tried looking but can't really get a clue. maybe you could point me in the right direction.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yavadan** [comment]
> > Let me know if you need any help testing, have plenty of spare Pi's, displays and SD cards.
> 
> feel free to checkout my fork^^ (branch fix/sibling2)

I wanted to test too,
Sorry if im missing something but i cant see any fork?

**Comment by lucataco** [comment]
@natur3kid Try the [steps here: ](https://askubuntu.com/questions/425027/how-to-recover-password-from-ubuntu-installed-on-sd-card)
@yavadan His fork is at [github.com/dadav/pwnagotchi](https://github.com/dadav/pwnagotchi/)

**Pull request merged**
