### PR TITLE
added support for timezones with - offset

### PR DESCRIPTION
**Pull request by gerard780**
introduced new regexp to better handle timestamps with a negative timezone offset like '2019-21-30T14:01:46.79231-05:00'

## Description
webgpsmap would fail to parse timestamps that had a '-' timezone offset

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Tested against sample gps handshakes at https://github.com/xenDE/pwnagotchi-plugin-webgpsmap/tree/master/handshakes.gps-map-test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by dadav** [comment]
I suggest we use the package `dateutil` to easily parse timestamps...

**Comment by gerard780** [comment]
I completely agree. I was just working with what was already available.

**Comment by xenDE** [comment]
i have tested old parsing and new dateutil solution with the testdata.

looks good, same timestamps and can handle negative timezone.

python3 ./datetest20200113.py
=> test 2019-11-28T04:44:46.79231Z
1574916287
1574916287

=> test 2019-11-12T11:37:09.4321+01:00
1573555029
1573555029

=> test 2019-11-12T11:37:09.367187+01:00
1573555029
1573555029

=> test 2019-11-16T00:19:18.00000000+0200
1573856358
1573856358

=> test 2019-11-14T12:30:41.097414739+01:00
1573731041
1573731041

=> test 2019-11-12T11:37:09.4321-01:00
1573562229
getTs2 error: not enough values to unpack (expected 3, got 2)


Testscript:
```
import re
import datetime
from dateutil.parser import parse

def getTs1(datestr):
	try:
		dateObj = parse(datestr)
		return int("%.0f" % dateObj.timestamp())
	except Exception as error:
		return f"getTs2 error: {error}"

def getTs2(datestr):
	try:
		date_iso_formated = datestr
		#fix timezone "Z": "2019-11-28T04:44:46.79231Z" >> "2019-11-28T04:44:46.79231+00:00"
		if date_iso_formated.endswith("Z"):
			date_iso_formated = date_iso_formated[:-1] + "+00:00"
		# bad microseconds fix: fill/cut microseconds to 6 numbers
		part1, part2, part3 = re.split('\.|\+', date_iso_formated)
		part2 = part2.ljust(6, '0')[:6]
		# timezone fix: 0200 >>> 02:00
		if len(part3) == 4:
			part3 = part3[1:2].rjust(2, '0') + ':' + part3[3:4].rjust(2, '0')
		date_iso_formated = part1 + "." + part2 + "+" + part3
		dateObj = datetime.datetime.fromisoformat(date_iso_formated)
		return int("%.0f" % dateObj.timestamp())
		
	except Exception as error:
		return f"getTs2 error: {error}"

testdata = {
	"2019-11-12T11:37:09.4321+01:00",
	"2019-11-12T11:37:09.4321-01:00",
	"2019-11-12T11:37:09.367187+01:00",
	"2019-11-14T12:30:41.097414739+01:00",
	"2019-11-28T04:44:46.79231Z",
	"2019-11-16T00:19:18.00000000+0200"
	}

for aDate in testdata:
	print(f"=> test {aDate}")
	print( getTs1(aDate) )
	print( getTs2(aDate) )
	print("")

```

**Comment by dadav** [comment]
> I completely agree. I was just working with what was already available.
> […](#)
> On Jan 13, 2020, at 1:59 PM, Daniel D. ***@***.***> wrote: ﻿ I suggest we use the package dateutil to easily parse timestamps... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I created a pr at your  repo^^

**Comment by devzspy** [comment]
This does not seem to work as expected for me.

**Expected:** Results displayed on the map

**Reality:** Receiving errors using the latest PR for webgpsmap.py ( https://github.com/evilsocket/pwnagotchi/blob/6001b7630b46fe19201bbf9872b811d5765763cd/pwnagotchi/plugins/default/webgpsmap.py )

**/var/log/pwnagotchi.log**
```
[2020-01-13 22:46:19,003] [INFO] [webgpsmap] Found 19 position-data files from 49 handshakes. Fetching positions ...
[2020-01-13 22:46:19,034] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,073] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,156] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,219] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,307] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,354] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,396] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,445] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,485] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,519] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,546] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,593] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,634] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,667] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,699] [ERROR] [webgpsmap] ValueError: not enough values to unpack (expected 3, got 2)
[2020-01-13 22:46:19,743] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,796] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,826] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,855] [ERROR] [webgpsmap] JSONDecodeError in: Expecting value: line 1 column 1 (char 0)
[2020-01-13 22:46:19,912] [INFO] [webgpsmap] loaded 0 positions
```

**GPS Capture:**

`{"Updated":"2020-01-07T01:48:09.00000000-0700","Latitude":33.30700315,"Longitude":-111.90985512,"NumSatellites":6,"Altitude":363.767333984375}`

**Comment by xenDE** [comment]
@devzspy works here.

```
=> test 2020-01-07T01:48:09.00000000-0700
1578386889
```
can you please test this with only the problematic handshake+json?

1) The "JSONDecodeError"'s looks like empty json files.
2) the "ValueError: not enough values to unpack (expected 3, got 2)" looks like you dont use this PR. https://github.com/evilsocket/pwnagotchi/pull/770/commits/6001b7630b46fe19201bbf9872b811d5765763cd

**Comment by dadav** [comment]
@gerard780 could you rebase pls? :)

**Comment by devzspy** [comment]
@xenDE 

The only problematic handshake that I had was listed above which does not load on the webgpsmap for me.

As for the others where you mentioned "The "JSONDecodeError"'s looks like empty json files." is correct. I checked some of my other files and they appeared empty.

As for the the "ValueError: not enough values to unpack (expected 3, got 2)" error 
 I am using PR https://github.com/evilsocket/pwnagotchi/commit/6001b7630b46fe19201bbf9872b811d5765763cd

**Comment by xenDE** [comment]
@devzspy: i will test and add better debug messages, if this PR is merged.

**Comment by devzspy** [comment]
@xenDE Please keep me updated and let me know if there is anything else you need from me to debug this issue.

**Pull request merged**
